--INSERT INTO CLIENTE(id, name, age, mail) VALUES('1', 'Ana', 21, 'ana@teste.com');

DROP TABLE IF EXISTS CLIENTE;
CREATE TABLE CLIENTE(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255),
age INT,
mail VARCHAR(255),
document VARCHAR(255)
);


DROP TABLE IF EXISTS PRODUCTO;
CREATE TABLE PRODUCTO(
id INT PRIMARY KEY AUTO_INCREMENT,
description VARCHAR(255),
brand VARCHAR(255),
category VARCHAR(255),
valor VARCHAR(255)
);

DROP TABLE IF EXISTS ORDERPAYMENT;
CREATE TABLE ORDERPAYMENT(
id INT PRIMARY KEY AUTO_INCREMENT,
dateOrder VARCHAR(255),
producto_id VARCHAR(255),
cliente_id VARCHAR(255)
);