apiVersion: v1
kind: Service
metadata:
  name: api-fastfood-service
spec:
  selector:
    app: app-fastfood
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080 # porta do service
    targetPort: 8080 # porta do container
    nodePort: 30080 # porta exposta no nรณ do cluster
